
export interface Employee {
  id_employee: string;
  name_employee: string;
  employee_code?: string;
  email?: string | null;
  phone?: string | null;
  role?: string | null;
  admission_date?: string;
  imss_registration_date?: string;
  position?: string;
  entry_time?: string;
  exit_time?: string;
  contract_type?: string;
  location?: string;
  gender?: string;
  age?: number | null;
  marital_status?: string;
  education_level?: string;
  education_status?: string;
  ine_code?: string;
  address?: string;
  street?: string;
  outdoor_number?: string;
  interior_number?: string;
  colony?: string;
  zip_code?: string;
  city?: string;
  state?: string;
  birth_place?: string;
  birth_date?: string;
  nss?: string;
  rfc?: string;
  curp?: string;
  children_count?: number | null;
  child1_name?: string;
  child1_birth_date?: string;
  child2_name?: string;
  child2_birth_date?: string;
  child3_name?: string;
  child3_birth_date?: string;
  child4_name?: string;
  child4_birth_date?: string;
  child5_name?: string;
  child5_birth_date?: string;
  beneficiaries_count?: number | null;
  beneficiary?: string; // Beneficiary 1
  beneficiary_relationship?: string;
  beneficiary_percentage?: string;
  beneficiary2_name?: string;
  beneficiary2_relationship?: string;
  beneficiary2_percentage?: string;
  beneficiary3_name?: string;
  beneficiary3_relationship?: string;
  beneficiary3_percentage?: string;
  infonavit_credit_number?: string;
  infonavit_factor?: string;
  blood_type?: string;
  weight?: string;
  height?: string;
  shirt_size?: string;
  diseases?: string;
  contract_expiration?: string;
  emergency_phone?: string;
  emergency_contact_name?: string;
  emergency_contact_relationship?: string;
  allergies?: string;
  pAut1: string;
  pAut2: string;
  pAut3: string;
  pCapSol: string;
  pComSol: string;
  pControlSol: string;
  pEdCats: string;
  pEdSol: string;
  pEstadisticas: string;
  pHistorial: string;
  pUsuarios: string;
  pVerCats?: string;
  pEliminarDocsRH?: string;
  pDescripcionesPuestos?: string;
  pPermisosVacaciones?: string;
  pAlertaContratos?: string;
  status?: boolean;
  imss_salary?: number;
  base_salary?: number;
  bonuses?: string;
  rehire_date?: string;
  rehire_document_path?: string;
  rehire_document_name?: string;
  is_dev?: boolean;
}